version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Overrides the local Redis URL to point to the Docker Redis container
      - REDIS_URL=redis://redis:6379/0 
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"